#!/bin/zsh
# Build and install everything from a source checkout:
#   ~/Applications/ShareToClaw.app, the sender CLI, and the relay LaunchAgent.
# Safe to re-run. (Homebrew users: `brew install grynn/tap/share-to-claw`
# then `share-to-claw setup` — this script is the from-source equivalent.)
set -euo pipefail

APP_NAME="ShareToClaw"
ROOT="$(cd "$(dirname "$0")" && pwd)"
INSTALLED="$HOME/Applications/$APP_NAME.app"
SUPPORT="$HOME/Library/Application Support/$APP_NAME"
SHIM="$HOME/.local/bin/share-to-claw"

UV="$(command -v uv 2>/dev/null || true)"
for candidate in "$HOME/.local/bin/uv" /opt/homebrew/bin/uv /usr/local/bin/uv; do
    [[ -n "$UV" ]] && break
    [[ -x "$candidate" ]] && UV="$candidate"
done
[[ -n "$UV" ]] || { echo "uv not found — install from https://astral.sh/uv"; exit 1; }

"$ROOT/scripts/build.sh" "$ROOT/build"

echo "== installing $INSTALLED"
mkdir -p "$HOME/Applications"
rm -rf "$INSTALLED"
cp -R "$ROOT/build/$APP_NAME.app" "$INSTALLED"

echo "== installing sender + CLI shim"
mkdir -p "$SUPPORT" "$(dirname "$SHIM")"
cp "$ROOT/sender/share_to_claw.py" "$SUPPORT/share_to_claw.py"
cp "$ROOT/agent/relay.plist.template" "$SUPPORT/relay.plist.template"
cat > "$SHIM" <<SHIM_EOF
#!/bin/sh
# Generated by $APP_NAME install.sh
case "\$1" in
    register)   exec "$ROOT/scripts/register.sh" --app "$INSTALLED" --script "$SUPPORT/share_to_claw.py" --uv "$UV" ;;
    unregister) exec "$ROOT/scripts/unregister.sh" --app "$INSTALLED" ;;
esac
exec "$UV" run "$SUPPORT/share_to_claw.py" "\$@"
SHIM_EOF
chmod +x "$SHIM"

"$ROOT/scripts/register.sh" --app "$INSTALLED" --script "$SUPPORT/share_to_claw.py" --uv "$UV"
echo "Done. CLI: $SHIM"
